# Generated by Django 2.0.5 on 2019-04-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(default='', max_length=500)),
                ('query_from', models.CharField(default='', max_length=50)),
                ('fetch_from', models.CharField(default='', max_length=50)),
                ('res_type', models.CharField(default='', max_length=50)),
                ('scene', models.CharField(default='', max_length=500)),
                ('is_resolve', models.NullBooleanField(default=None)),
            ],
        ),
    ]
