# Generated by Django 2.0.5 on 2019-04-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizhi', '0002_auto_20190425_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultDetail',
        ),
    ]
