# Generated by Django 2.0.5 on 2019-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lizhi', '0003_delete_resultdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(default='', max_length=500)),
                ('query_from', models.CharField(default='', max_length=50)),
                ('sg_res_type', models.CharField(default='', max_length=50)),
                ('bd_res_type', models.CharField(default='', max_length=50)),
                ('sg_scene', models.CharField(default='', max_length=500)),
                ('bd_scene', models.CharField(default='', max_length=500)),
                ('is_resolve', models.NullBooleanField(default=None)),
            ],
        ),
    ]
