# Generated by Django 2.0.5 on 2019-04-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizhi', '0004_resultdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultDetail',
        ),
    ]
