# Generated by Django 2.0.5 on 2019-04-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lizhi', '0005_delete_resultdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(default='', max_length=500)),
                ('query_from', models.CharField(default='', max_length=50)),
                ('sg_res_type', models.CharField(default='', max_length=50)),
                ('bd_res_type', models.CharField(default='', max_length=50)),
                ('sg_scene', models.CharField(default='', max_length=500)),
                ('bd_scene', models.CharField(default='', max_length=500)),
                ('is_resolve', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='resultdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lizhi.Task'),
        ),
    ]
