# Generated by Django 2.1.2 on 2019-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lizhi', '0006_auto_20190426_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultdetail',
            name='is_resolve',
        ),
        migrations.AddField(
            model_name='resultdetail',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
