# Generated by Django 2.0.5 on 2019-04-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizhi', '0007_auto_20190426_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultdetail',
            name='task',
        ),
        migrations.DeleteModel(
            name='ResultDetail',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
